
import java.awt.Color;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author alexm
 */
public class bienvenida extends javax.swing.JPanel {

    /**
     * Creates new form bienvenida
     */
    public bienvenida() {
        initComponents();
        iniciarStyle();
    }
    
    private void iniciarStyle() {       
        titulo.putClientProperty("FlatLaf.style", "font: bold $h1.regular.font");
        titulo.setForeground(Color.black);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jCheckBox1 = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(255, 255, 255));

        titulo.setText("Bienvenid@s");

        jLabel2.setText("<html><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam tristique lectus suscipit, consequat orci at, aliquam nulla. Aliquam id ante ex. Cras efficitur diam sapien, vitae mollis purus fringilla molestie. Mauris massa odio, dapibus et ultrices vitae, semper ac urna. Pellentesque vel purus non nisl aliquam rutrum. Vivamus fermentum, ante non laoreet dictum, tortor magna pharetra mi, a malesuada quam erat vitae nunc. Mauris facilisis, risus id ultricies pulvinar, velit orci porttitor enim, nec pretium purus erat ac dui. Nullam ullamcorper urna vitae lacus tristique tempor. Etiam tincidunt sodales volutpat. Vestibulum vel ipsum iaculis, finibus nisi in, tempor sapien.</p></html>");

        jLabel3.setText("<html><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam tristique lectus suscipit, consequat orci at, aliquam nulla. Aliquam id ante ex. Cras efficitur diam sapien, vitae mollis purus fringilla molestie. Mauris massa odio, dapibus et ultrices vitae, semper ac urna. Pellentesque vel purus non nisl aliquam rutrum. Vivamus fermentum, ante non laoreet dictum, tortor magna pharetra mi, a malesuada quam erat vitae nunc. Mauris facilisis, risus id ultricies pulvinar, velit orci porttitor enim, nec pretium purus erat ac dui. Nullam ullamcorper urna vitae lacus tristique tempor. Etiam tincidunt sodales volutpat. Vestibulum vel ipsum iaculis, finibus nisi in, tempor sapien.</p></html>");

        jRadioButton1.setText("jRadioButton1");

        jCheckBox1.setText("jCheckBox1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox1)
                        .addGap(118, 118, 118)))
                .addGap(147, 147, 147))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton1)
                    .addComponent(jCheckBox1))
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
